Repository National-Digital-Twin/iris-api, pull requests merged in 2025-09, with the labels that each got.

#82 revert: [DPAV-1292] epc endpoints
  Makefile
  api/alembic/versions/2215b32f49a9_008_create_uk_ward_table_view.py
  api/alembic/versions/8f985d72a651_009_create_uk_region_table_view.py
  api/alembic/versions/993c0cf8ea04_010_create_uk_district_table_view.py
  api/alembic/versions/d12ce7dc9019_003_create_structure_unit_table.py
  api/alembic/versions/d99eb3e1e4ab_011_create_uk_counties_table_view.py
  developer-resources/load_gpkg_to_postgis.py
  entrypoint.sh
Labels: fix

#86 feature: (DPAV-1481) add os ngd roof columns
  api/alembic/versions/10f244f0a95e_012_alter_structure_unit_add_roof_attributes.py
  api/alembic/versions/d12ce7dc9019_003_create_structure_unit_table.py
Labels: feature

#85 feat(DPAV-1594): new api queries for os ngd buildings data
  CHANGELOG.md
  Makefile
  api/mappers.py
  api/models/dto_models.py
  api/query.py
  api/routes.py
Labels: documentation, feature

#87 feature: (DPAV-1579) add UPRN and roof shape
  api/alembic/versions/2215b32f49a9_008_create_uk_ward_table_view.py
  api/alembic/versions/8f985d72a651_009_create_uk_region_table_view.py
  api/alembic/versions/993c0cf8ea04_010_create_uk_district_table_view.py
  api/alembic/versions/cf408e1ffd0e_013_add_uprn_structure_unit.py
  api/alembic/versions/d99eb3e1e4ab_011_create_uk_counties_table_view.py
Labels: feature

#91 feature: [DPAV-1453] add underlying geometry data for Wales
  Makefile
  api/alembic/versions/cc816c325e2a_014_add_country_table.py
  developer-resources/load_gpkg_to_postgis.py
  entrypoint.sh
Labels: feature

#89 feat(DPAV-1594): new postgis fallback option for os ngd buildings data
  api/mappers.py
  api/models/dto_models.py
  api/query.py
  api/routes.py
  api/utils.py
Labels: feature

#93 feat(DPAV-1594): os ngd roof shape
  api/mappers.py
  api/models/dto_models.py
  api/query.py
  api/routes.py
Labels: feature

#97 feat(DPAV-1731): update to migrations to identify residential dwellings
  api/alembic/versions/0e6126841f0c_update_buildings_is_residential.py
  api/alembic/versions/473ce669077d_update_buildings_epc_is_residential.py
  api/alembic/versions/cc816c325e2a_014_add_country_table.py
Labels: feature

#100 feature(DPAV-1731): efficiency improvements to migration queries
  api/alembic/versions/0e6126841f0c_015_update_buildings_is_residential.py
  api/alembic/versions/473ce669077d_016_update_buildings_epc_is_residential.py
Labels: feature
